# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('remind_date', models.DateTimeField()),
                ('repeat_remind', models.BooleanField(default=False)),
                ('remind_location', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('google_auth', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.User'),
        ),
    ]
